module ApplicationHelper

  def countries
    [
      ["Argentina", "AR"],
      ["Angola", "AO"],
      ["Austria", "AT"],
      ["Australia", "AU"],
      ["Aruba", "AW"],
      ["Åland Islands", "AX"],
      ["Bosnia and Herzegovina", "BA"],
      ["Belgium", "BE"],
      ["Bulgaria", "BG"],
      ["Bolivia", "BO"],
      ["Brazil", "BR"],
      ["The Bahamas", "BS"],
      ["Canada", "CA"],
      ["Switzerland", "CH"],
      ["China", "CN"],
      ["Colombia", "CO"],
      ["Costa Rica", "CR"],
      ["Cuba", "CU"],
      ["Czech Republic", "CZ"],
      ["Germany", "DE"],
      ["Denmark", "DK"],
      ["Dominican Republic", "DO"],
      ["Ecuador", "EC"],
      ["Spain", "ES"],
      ["Finland", "FI"],
      ["France", "FR"],
      ["United Kingdom", "GB"],
      ["England", "GB-ENG"],
      ["Northern Ireland", "GB-NIR"],
      ["Scotland", "GB-SCT"],
      ["Wales", "GB-WLS"],
      ["Greece", "GR"],
      ["Guatemala", "GT"],
      ["Hong Kong", "HK"],
      ["Honduras", "HN"],
      ["Croatia", "HR"],
      ["Hungary", "HU"],
      ["Indonesia", "ID"],
      ["Ireland", "IE"],
      ["India", "IN"],
      ["Israel", "IL"],
      ["Iceland", "IS"],
      ["Italy", "IT"],
      ["Japan", "JP"],
      ["Kazakhstan", "KZ"],
      ["Lesotho", "LS"],
      ["Luxembourg", "LU"],
      ["Madagascar", "MG"],
      ["Martinique", "MQ"],
      ["Malta", "MT"],
      ["Mauritius", "MU"],
      ["Mexico", "MX"],
      ["Mozambique", "MZ"],
      ["Nigeria", "NG"],
      ["Netherlands", "NL"],
      ["Norway", "NO"],
      ["Peru", "PE"],
      ["Pakistan", "PK"],
      ["Philippines", "PH"],
      ["Poland", "PL"],
      ["Puerto Rico", "PR"],
      ["Portugal", "PT"],
      ["Paraguay", "PY"],
      ["Réunion", "RE"],
      ["Romania", "RO"],
      ["Russia", "RU"],
      ["Seychelles", "SC"],
      ["Sweden", "SE"],
      ["Singapore", "SG"],
      ["Slovenia", "SI"],
      ["Sao Tome and Principe", "ST"],
      ["Slovakia", "SK"],
      ["Tunisia", "TN"],
      ["Turkey", "TR"],
      ["Ukraine", "UA"],
      ["United States", "US"],
      ["Uruguay", "UY"],
      ["Venezuela", "VE"],
      ["South Africa", "ZA"],
      ["Zimbabwe", "ZW"]
    ]
  end



  
