# Country Seed Data - IF IT"S COMMENTED OUT IT NEEDS A NEW FLAG IMAGE! DO NOT USE PNG! ONLY GIF OR JPG
Country.create!(name: "Argentina", abbreviation: "AR", flag_img_url: "https://cdn3.volusion.com/jmlfn.xfvpt/v/vspfiles/photos/argentina-flag-2.jpg?1433246627")
Country.create!(name: "Angola", abbreviation: "AO", flag_img_url: "http://www.lse.ac.uk/study/informationForInternationalStudents/countryRegion/africa/angola/angolanFlag.gif")
Country.create!(name: "Austria", abbreviation: "AT", flag_img_url: "http://www.mofa.gov.tw/Upload/Sites/FlagUrlLink/5cb1c4d0-43f4-4d8a-b92f-4ee598153b75.GIF")
Country.create!(name: "Australia", abbreviation: "AU", flag_img_url: "https://media1.britannica.com/eb-media/78/6078-004-A4F193DB.jpg")
Country.create!(name: "Aruba", abbreviation: "AW", flag_img_url: "http://etc.usf.edu/clipart/71900/71974/71974_aw_flag_col_lg.gif")
Country.create!(name: "Aland Island", abbreviation: "AX", flag_img_url: "http://www.crwflags.com/fotw/images/a/ax.gif")
Country.create!(name: "Bosnia", abbreviation: "BA", flag_img_url: "http://cdn.wonderfulengineering.com/wp-content/uploads/2015/07/bosnia-flag-6.png")
Country.create!(name: "Belgium", abbreviation: "BE", flag_img_url: "http://www.europe-trips.eu/Belgium/Belgium-Flag.jpg")
Country.create!(name: "Bulgaria", abbreviation: "BG", flag_img_url: "https://www.worldflags.es/imagenes/productos/1451p_BULGARIA.JPG")
Country.create!(name: "Bolivia", abbreviation: "BO", flag_img_url: "http://thefactfile.org/wp-content/uploads/2016/03/bolivia-flag.gif")
Country.create!(name: "Brazil", abbreviation: "BR", flag_img_url: "http://culture-inc.com/eng/wp-content/uploads/2014/06/bandeira_do_brasil2.jpg")
Country.create!(name: "The Bahamas", abbreviation: "BS", flag_img_url: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_the_Bahamas_%28WFB_2004%29.gif")
Country.create!(name: "Canada", abbreviation: "CA", flag_img_url: "http://flaglane.com/download/canadian-flag/canadian-flag-medium.jpg")
Country.create!(name: "Switzerland", abbreviation: "CH", flag_img_url: "http://flaglane.com/download/swiss-flag/swiss-flag-medium.jpg")
Country.create!(name: "China", abbreviation: "CN", flag_img_url: "http://flaglane.com/download/chinese-flag/chinese-flag-medium.jpg")
Country.create!(name: "Colombia", abbreviation: "CO", flag_img_url: "http://flaglane.com/download/colombian-flag/colombian-flag-medium.jpg")
Country.create!(name: "Costa Rica", abbreviation: "CR", flag_img_url: "http://flaglane.com/download/costa-rican-flag/costa-rican-flag-medium.jpg")
Country.create!(name: "Cuba", abbreviation: "CU", flag_img_url: "http://flaglane.com/download/cuban-flag/cuban-flag-medium.jpg")
Country.create!(name: "Czech Republic", abbreviation: "CZ", flag_img_url: "http://flaglane.com/download/czech-flag/czech-flag-medium.jpg")
Country.create!(name: "Germany", abbreviation: "DE", flag_img_url: "http://flaglane.com/download/german-flag/german-flag-medium.jpg")
# Country.create!(name: "Denmark", abbreviation: "DK", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Denmark.png")
# Country.create!(name: "Dominican Republic", abbreviation: "DO", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Dominican-Republic.png")
# Country.create!(name: "Ecuador", abbreviation: "EC", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Ecuador.png")
# Country.create!(name: "Spain", abbreviation: "ES", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Spain.png")
# Country.create!(name: "Finland", abbreviation: "FI", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Finland.png")
# Country.create!(name: "France", abbreviation: "FR", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-France.png")
# Country.create!(name: "United Kingdom", abbreviation: "GB", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-United-Kingdom.png")
Country.create!(name: "England", abbreviation: "GB-ENG", flag_img_url: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Old_union_jack.gif/320px-Old_union_jack.gif")
Country.create!(name: "Northern Ireland", abbreviation: "GB-NIR", flag_img_url: "http://hasankocabas.com.tr/files/yuklenenler/resim/A21.png")
# Country.create!(name: "Guatemala", abbreviation: "GB-SCT", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Guatemala.png")
Country.create!(name: "Hong Kong", abbreviation: "HK", flag_img_url: "http://www.flags.net/images/largeflags/CHIN0100.GIF")
# Country.create!(name: "Honduras", abbreviation: "HN", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Honduras.png")
# Country.create!(name: "Croatia", abbreviation: "HR", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Croatia.png")
# Country.create!(name: "Hungary", abbreviation: "HU", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Hungary.png")
# Country.create!(name: "Indonesia", abbreviation: "ID", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Indonesia.png")
# Country.create!(name: "Ireland", abbreviation: "IE", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Ireland.png")
# Country.create!(name: "India", abbreviation: "IN", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-India.png")
# Country.create!(name: "Israel", abbreviation: "IL", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Israel.png")
# Country.create!(name: "Iceland", abbreviation: "IS", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Iceland.png")
# Country.create!(name: "Italy", abbreviation: "IT", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Italy.png")
# Country.create!(name: "Japan", abbreviation: "JP", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Japan.png")
# Country.create!(name: "Kazakhstan", abbreviation: "KZ", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Kazakhstan.png")
# Country.create!(name: "Lesotho", abbreviation: "LS", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Lesotho.png")
# Country.create!(name: "Luxembourg", abbreviation: "LU", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Luxembourg.png")
# Country.create!(name: "Madagascar", abbreviation: "MG", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Madagascar.png")
Country.create!(name: "Martinique", abbreviation: "MQ", flag_img_url: "http://www.crwflags.com/fotw/images/m/mq-unof.gif")
# Country.create!(name: "Malta", abbreviation: "MT", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Malta.png")
# Country.create!(name: "Mauritius", abbreviation: "MU", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Mauritius.png")
# Country.create!(name: "Mexico", abbreviation: "MX", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Mexico.png")
# Country.create!(name: "Mozambique", abbreviation: "MZ", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Mozambique.png")
# Country.create!(name: "Nigeria", abbreviation: "NG", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Nigeria.png")
# Country.create!(name: "Netherlands", abbreviation: "NL", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Netherlands.png")
# Country.create!(name: "Norway", abbreviation: "NO", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Norway.png")
# Country.create!(name: "Peru", abbreviation: "PE", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Peru.png")
# Country.create!(name: "Pakistan", abbreviation: "PK", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Pakistan.png")
# Country.create!(name: "Phillipines", abbreviation: "PH", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Philippines.png")
# Country.create!(name: "Poland", abbreviation: "PL", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Poland.png")
Country.create!(name: "Puerto Rico", abbreviation: "PR", flag_img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/255px-Flag_of_Puerto_Rico.svg.png")
# Country.create!(name: "Portugal", abbreviation: "PT", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Portugal.png")
# Country.create!(name: "Paraguay", abbreviation: "PY", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Paraguay.png")
Country.create!(name: "Island of Réunion", abbreviation: "RE", flag_img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Proposed_flag_of_R%C3%A9union_%28VAR%29.svg/200px-Proposed_flag_of_R%C3%A9union_%28VAR%29.svg.png")
# Country.create!(name: "Romania", abbreviation: "RO", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Romania.png")
# Country.create!(name: "Russia", abbreviation: "RU", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Russia.png")
# Country.create!(name: "Seychelles", abbreviation: "SC", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Seychelles.png")
# Country.create!(name: "Sweden", abbreviation: "SE", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Sweden.png")
# Country.create!(name: "Singapore", abbreviation: "SG", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Singapore.png")
# Country.create!(name: "Slovenia", abbreviation: "SI", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Slovenia.png")
# Country.create!(name: "Sao Tome and Principe", abbreviation: "ST", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Sao-Tome-and-Principe.png")
# Country.create!(name: "Slovakia", abbreviation: "SK", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Slovakia.png")
# Country.create!(name: "Tunisia", abbreviation: "TN", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Tunisia.png")
# Country.create!(name: "Turkey", abbreviation: "TR", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Turkey.png")
# Country.create!(name: "Ukraine", abbreviation: "UA", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Ukraine.png")
# Country.create!(name: "United States", abbreviation: "US", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-United-States-of-America.png")
# Country.create!(name: "Uraguay", abbreviation: "UY", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Uraguay.png")
# Country.create!(name: "Venezuela", abbreviation: "VE", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Venezuela.png")
# Country.create!(name: "South Africa", abbreviation: "ZA", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-South-Africa.png")
# Country.create!(name: "Zimbabe", abbreviation: "ZW", flag_img_url: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Zimbabwe.png")
